### ISSUE TITLE
Analyzer warnings

### ISSUE THREAD

**Issue by srawlins** [matanlurey/file#4]
Analyzer warnings:

In [sync.dart](https://github.com/matanlurey/file/blob/master/lib/src/sync.dart): getParentPath and FileSystemEntityException are imported but not used.

In [file_system_entity.dart](https://github.com/matanlurey/file/blob/master/lib/src/interface/file_system_entity.dart), `@override` annotates FileSystemEntityException's `message`, which is not overriding anything.

**Comment by srawlins** [comment]
😦

**Comment by tvolkert** [comment]
Why the frowny face?

**Comment by srawlins** [comment]
Was this just closed and not fixed?

**Comment by tvolkert** [comment]
Oh no, it was über-fixed - the whole library has been reimplemented and now provides a direct abstraction of the `dart:io` interfaces 😵

**Comment by tvolkert** [comment]
(mostly done - still adding tests, and the README needs to be updated, then we'll push to pub)

**Comment by srawlins** [comment]
Ah, I see. Woohoo!
